services:
  db:
    image: postgres:16
    container_name: rrhh_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ:-America/Santiago}
      PGTZ: ${PGTZ:-America/Santiago}
    command: ["postgres", "-c", "timezone=America/Santiago"]
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped

  web:
    build: ./web
    container_name: rrhh_web
    environment:
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DATABASE_URL: ${DATABASE_URL}
      FLASK_ENV: ${FLASK_ENV:-production}
      SECRET_KEY: ${SECRET_KEY}
      TZ: ${TZ:-America/Santiago}

      NEXTCLOUD_MOUNT_ROOT: ${NEXTCLOUD_MOUNT_ROOT:-/mnt/GrupoCS-Nextcloud}
      NEXTCLOUD_DOC_ROOT: ${NEXTCLOUD_DOC_ROOT:-DOCUMENTACION LABORAL}
      NEXTCLOUD_ROOT: ${NEXTCLOUD_ROOT:-/mnt/GrupoCS-Nextcloud/DOCUMENTACION LABORAL}
      NEXTCLOUD_WEBDAV_URL: ${NEXTCLOUD_WEBDAV_URL:-}
      NEXTCLOUD_USERNAME: ${NEXTCLOUD_USERNAME:-}
      NEXTCLOUD_PASSWORD: ${NEXTCLOUD_PASSWORD:-}
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./web/app:/app/app:rw
      - ./web/migrations:/app/migrations:rw
      - /mnt/GrupoCS-Nextcloud:/mnt/GrupoCS-Nextcloud:rw
      - ./data:/data
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
