"""add inasistencias

Revision ID: 546182cf4817
Revises: b0c18a148082
Create Date: 2026-01-13 15:04:40.594342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546182cf4817'
down_revision = 'b0c18a148082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inasistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('minutos_ausentes', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=80), nullable=False),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('creado_por_user_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(tipo = 'DIA' AND minutos_ausentes IS NULL) OR (tipo = 'HORAS' AND minutos_ausentes IS NOT NULL AND minutos_ausentes > 0)", name='ck_inasistencias_minutos_por_tipo'),
    sa.CheckConstraint("tipo IN ('DIA','HORAS')", name='ck_inasistencias_tipo'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['creado_por_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inasistencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inasistencias_contrato_id'), ['contrato_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inasistencias_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_inasistencias_trabajador_id'), ['trabajador_id'], unique=False)

    op.drop_table('contratos_import')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratos_import',
    sa.Column('rut_sin_dv', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('empleador_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('obra_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cargo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_contrato', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_termino', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('jornada', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('horas_semanales', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sueldo_base', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('asignacion_movilizacion', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('asignacion_colacion', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('asignacion_herramientas', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('estado_contrato', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('causal_termino', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('fecha_finiquito', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('horario_id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    with op.batch_alter_table('inasistencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inasistencias_trabajador_id'))
        batch_op.drop_index(batch_op.f('ix_inasistencias_fecha'))
        batch_op.drop_index(batch_op.f('ix_inasistencias_contrato_id'))

    op.drop_table('inasistencias')
    # ### end Alembic commands ###
