"""create anexos indefinidos

Revision ID: aa3e2df5c1ee
Revises: 
Create Date: 2026-01-11 20:44:58.639065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa3e2df5c1ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anexos_indefinido_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('empleador_id', sa.Integer(), nullable=True),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.Column('fecha_anexo', sa.Date(), nullable=False),
    sa.Column('fecha_indefinido_desde', sa.Date(), nullable=False),
    sa.Column('fecha_termino_referencial', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('formato', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('docx_nombre', sa.String(length=255), nullable=True),
    sa.Column('docx_ruta', sa.Text(), nullable=True),
    sa.Column('pdf_nombre', sa.String(length=255), nullable=True),
    sa.Column('pdf_ruta', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['empleador_id'], ['empleadores.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anexos_indefinido_contrato', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anexos_indefinido_contrato_contrato_id'), ['contrato_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anexos_indefinido_contrato_empleador_id'), ['empleador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anexos_indefinido_contrato_obra_id'), ['obra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anexos_indefinido_contrato_trabajador_id'), ['trabajador_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anexos_indefinido_contrato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anexos_indefinido_contrato_trabajador_id'))
        batch_op.drop_index(batch_op.f('ix_anexos_indefinido_contrato_obra_id'))
        batch_op.drop_index(batch_op.f('ix_anexos_indefinido_contrato_empleador_id'))
        batch_op.drop_index(batch_op.f('ix_anexos_indefinido_contrato_contrato_id'))

    op.drop_table('anexos_indefinido_contrato')
    # ### end Alembic commands ###
